### ISSUE TITLE
Make `KEVMCheats` a Foundry lib

### ISSUE THREAD

**Issue by iFrostizz** [runtimeverification/kontrol#11]
We could setup a repo under the `runtimeverification` Github organization to allow to install the `KEVMCheats` library through `forge i runtimeverification/KEVMCheats` (or similar). This would be more convenient and less error-prone due to versioning issues than copy and pasting the file as we are currently doing.

Some example of existing libraries for inspiration:

- https://github.com/foundry-rs/forge-std
- https://github.com/refcell/unix
- https://github.com/memester-xyz/surl

**Comment by palinatolmach** [comment]
Agree that it would be nice to do; Halmos also uses this approach to distribute their cheatcode file: 
```
The Halmos cheatcodes can be installed like any other Solidity dependencies:

forge install a16z/halmos-cheatcodes
```

**Comment by palinatolmach** [comment]
I got user feedback suggesting that our current approach is inconvenient to use and goes against industry standards, so I'm suggesting bumping the priority of this issue (especially considering that it's relatively low-effort).

**Comment by RaoulSchaffranek** [comment]
The [ercx-library](https://github.com/runtimeverification/ercx-library) is an example of a library installable via `forge install runtimeverification/ercx-library`. This project is itself a Foundry project and highlights a [remmapings.txt](https://github.com/runtimeverification/ercx-library/blob/master/remappings.txt) file that contains the necessary configuration to link the library correctly. IIRC, that's all we needed to do.

**Comment by JuanCoRo** [comment]
Libray's ready [here](https://github.com/runtimeverification/kontrol-cheatcodes/tree/master). We may want to do some of the following:
- [ ] Make `KontrolCheatcodes` inherit `Test`, so that users only have to import one library
- [ ] Make sure we have some CI to check that the current version of the Cheatcodes library doesn't break anything
- [ ] At some point, replace `kevm` with `kontrol` to do `kontrol.cheatcode()` in favour of `kevm.cheatcode()`

Let me know if I missed anything!
