### ISSUE TITLE
Rehaul default KCFG file names

### ISSUE THREAD

**Issue by palinatolmach** [runtimeverification/kontrol#16]
As @lucasmt said, currently, the name of the file where KCFG is stored is computed as a hash, which means that every time there is an update in the analyzed contract or KEVM, the file name changes too. To make it more convenient, perhaps we should rehaul the way KCFG files are named to allow easier comparison between different versions of the same KCFG.

**Comment by lucasmt** [comment]
To expand on this, I think there are two scenarios where the current handling of KCFGs is inconvenient:

1. If you run `kevm foundry-prove` and generate a KCFG, then make a change to the code and rekompile, you can no longer call `kevm foundry-show` on the old KCFG, because the tool will be expecting a different filename. Instead, you need to rename the old KCFG to the new filename. But if you have many KCFGs in your `apr_proofs` directory, you might not know anymore which of those is the KCFG you need to rename.

2. Currently, if we want to save KCFGs to inspect or resume later, we manually copy them to a different directory. We then copy them back to `apr_proofs` when we want to use them again. But we need to know what filename to copy them to, because it probably has changed since then. It's not always easy to find out what the new filename should be.

I suggested changing the file naming conventions as one way to address these issues, but there are other alternatives as well. One option that would make (2) easier is if we had commands like
```
kevm foundry-save-kcfg TestContract.testName path/to/file.json
kevm foundry-load-kcfg TestContract.testName path/to/file.json
```
that handle the copying for you, calculating the hash for `TestContract.testName` and then copying the appropriate KCFG file to or from the path you provided.

For (1), it might be good to have an easy way to check what test a KCFG file corresponds to. That information is present inside the file itself, but it's hard to check because the file tends to be _very_ large and all in one line.

**Comment by lucasmt** [comment]
Note: I realize that there was recently an update to the tool that saves KCFGs to multiple files instead of just one. I haven't tried it out yet, so my observations are based on the old system. But I expect that they can be adapted to the new system as well.

**Comment by nwatson22** [comment]
Is there a reason we opted to use hashes as the filenames in the first place? The new system removes one level of hashing so the test is stored in a directory called something like `ContractName.test_name:hash`. I'm wondering if we could just remove the hash portion. It's tied into the digest system which is used to determine if proofs should be reinitialized, solidity code recompiled, etc, so we need to be sure whatever changes we make don't break that.

**Comment by iFrostizz** [comment]
@nwatson22 this is a good idea, what we could do would be to store this digest in a `digest` file that is in the `ContractName.test_name` and instead rename proof directories with an incrementing number that increments once the proof changes `ContractName.test_name:1` for instance. Then we could `foundry-show` proofs from their `ContractName.test_name` and index.

**Comment by iFrostizz** [comment]
To calculate the contract hash, we derive it from solc output: https://github.com/runtimeverification/evm-semantics/blob/master/kevm-pyk/src/kontrol/solc_to_k.py#L283-L285
This makes it very sensitive to change, if the user changes his configuration. This is a highlight of all of the parameters that may change from the compiler output. If any of these change the even slightest, the digest will be different: https://docs.soliditylang.org/en/v0.8.20/using-the-compiler.html#output-description

**Comment by lucasmt** [comment]
As I discussed with @iFrostizz earlier today, I agree with the mechanism proposed by him. I would suggest the following behavior (but I'm open to other ideas):

- By default, have `foundry-prove` and `foundry-show` use the most recent version (highest index), but have a command-line option to specify a previous version.
- If `foundry-prove` is run without `--reinit`, calculate the digest and see if it matches the specified version. Otherwise, output an error message to say the kompiled code has changed.
- If `foundry-prove` is run with `--reinit`, increment the index and create a new version.
- For `foundry-show` I don't think we need to check if the digest matches, because it just reads the KCFG.

We also need to consider other commands that modify the KCFG, like `foundry-remove-node` and `foundry-section-edge`. `foundry-section-edge` has to do steps of execution, so we should probably also check that the digest matches. But I think for `foundry-remove-node` that's not necessary.
