### ISSUE TITLE
Support `deal` cheatcode for tokens

### ISSUE THREAD

**Issue by palinatolmach** [runtimeverification/kontrol#20]
Foundry [supports]( https://github.com/foundry-rs/forge-std/blob/1cefc0e4e3d2a1f604c654004c90bd6701b2b5e2/src/StdCheats.sol#L725C8-L725C8) several `deal` signatures: one for granting ETH to an address and two — for ERC20 tokens (with and without `totalSupply` adjustment). In Kontrol, we only support the one that sets the ETH balance: https://github.com/runtimeverification/evm-semantics/blob/9a6277d1b908300f95ca0344bccf1cbc9261a2b1/include/kframework/foundry.md?plain=1#L331.

The logic of ERC20 balance adjustment is [implemented](https://github.com/foundry-rs/forge-std/blob/1cefc0e4e3d2a1f604c654004c90bd6701b2b5e2/src/StdCheats.sol#L725C8-L725C8) in the Foundry's `deal`, but it causes performance issues when analyzed with Kontrol, so further investigation is needed.

**Comment by RaoulSchaffranek** [comment]
Hi there! 😊

I remember grappling with similar issues when working on ERCX. I'd love to share some insights from that experience which might be helpful:

First, let's pause and ponder: "Why exactly do we need the deal-cheat code?" 

The root cause is ERC20 leaves the method of bringing tokens into existence open to individual implementations. For instance, some tokens might have a fixed supply controlled by the owner, who's then tasked with distributing them to end users. Others might offer permissionless mint functions. Essentially, there's a bouquet of implementations out there.

Testing becomes a tad tricky when dealing with arbitrary tokens. If you know the specific token implementation, there's no need for the deal cheat code. Just invoke the appropriate minting function! But for arbitrary tokens, there's that element of the unknown. Admittedly, we can fine-tune our tests if we focus on a limited set of tokens. However, this method loses its charm with larger sets.

Foundry's deal cheat code offers a heuristic for minting. It presumes that tokens utilize a mapping from addresses to balances in the storage and ambitiously attempt to overwrite these spots. A few challenges, though:
1. Unexpected results if the contract's balance mapping is elsewhere.
2. Potential discrepancies if the token's rebasing or only retains a normalized amount relative to a scaled amount.

In ERCX with have a test case that tries to detect these short-comings of the deal cheat code: https://github.com/runtimeverification/ercx-library/issues/166


Now, what's the alternative?
Well, instead of the cheat code, we could presume that a user's balance stands at a certain number:

```Solidity
assume(balanceOf(user) == X);
```

The snag? This doesn't gel well with Foundry. But KEVM? That's a different story. KEVM lets us make storage assumptions. Plus, this method adheres to ERC20 standards and should be compatible with rebasing tokens. A cherry on top? It's a more elegant approach, relying on the `balanceOf` function (an interface) rather than delving into the nitty-gritty of storage slots.

Would love to hear your thoughts and explore how we can further refine this! Cheers! 🚀

**Comment by palinatolmach** [comment]
Many thanks @RaoulSchaffranek! I agree that instead of supporting Foundry's `deal` cheatcode for tokens, we can utilize symbolic storage and `vm.assume()` supported by KEVM to make assumptions about user balances. Closing this issue.
