### ISSUE TITLE
Concretize `setUp` and deployment

### ISSUE THREAD

**Issue by palinatolmach** [runtimeverification/kontrol#222]
Suggested by @RaoulSchaffranek and @JuanCoRo. We are facing a recurring issue with the complexity of deployment scripts, cause executing complex `setUp` in Kontrol is challenging. To streamline this process, we could use an alternative approach: generating the deployment transaction with a Foundry script and simulating it with Kontrol. This would allow us to initiate our tests directly from the state created by this deployment. If we can get the state of the contract(s) after the execution of `setUp` in Foundry, we could "load" these information about the created and accessed contracts to the initial configuration in a test proof.

**Comment by RaoulSchaffranek** [comment]
After further consideration, we'd like to find a method for simulating JSON-RPC calls and then using the resultant state to initiate our test cases. In this context, I've observed that KEVM includes a [module](https://github.com/runtimeverification/evm-semantics/blob/master/kevm-pyk/src/kevm_pyk/kproj/evm-semantics/json-rpc.md) dedicated to handling JSON-RPC calls. However, this module appears to primarily focus on defining syntax and enforcing specific validation rules rather than simulating the transactions.

https://ethereum.org/en/developers/docs/apis/json-rpc/

**Comment by anvacaru** [comment]
We can now use the foundry [stop-and-return-state-diff](https://book.getfoundry.sh/cheatcodes/stop-and-return-state-diff) feature in kontrol to generate summaries of the `setUp` functions as JSON objects. Using these, we can either generate a Solidity contract ([source here](https://github.com/runtimeverification/kontrol/pull/221)) that applies the changes using cheat codes, or insert the state-diff directly in the `init_term` of a proof  with `fast-summarization` ([source here](https://github.com/runtimeverification/kontrol/issues/266)). Closing this issue for now.
