### ISSUE TITLE
Checking `--bmc-depth` slows proofs down over time

### ISSUE THREAD

**Issue by RaoulSchaffranek** [runtimeverification/kontrol#283]
When using `--break-every-step`, we produce very large kcfgs. Checking the `--bmc-depth` then becomes an increasingly expensive operation. The overhead only becomes noticeable when we have more than 1000 nodes, and by the time we reach 5000 nodes, it becomes the main bottleneck of the execution, adding some seconds for each node.

**Comment by PetarMax** [comment]
For KEVM specifically, a hashtable cache where the visited program counters would be keys and a list/set of KCFG node ids at which the program counter appears would be the corresponding value would significantly reduce the search space. I'm not sure how to implement this modularly given the current infrastructure, though, since it would introduce additional state.
