### ISSUE TITLE
Use proper configuration in non-test constructors

### ISSUE THREAD

**Issue by palinatolmach** [runtimeverification/kontrol#457]
Follow up to https://github.com/runtimeverification/kontrol/pull/404. 

As identified by @PetarMax, an adjustment on how constructors are run for non-tests is needed. Specifically, this function:
```solidity
    function run_constructor() public {
        assert(flag);
    }
```
which is not a test, and so its constructor should be run with a symbolic `CONTRACT_ID`. However, it’s run with a concrete one (`Foundry.address_TEST_CONTRACT()`), since that’s what is done when a constructor is reached. This test fails with the `SLOAD 27` error .

A likely fix for that is to allow for the constructor to be executed with a symbolic configuration similar to non-tests. However, it is possible that tests and non-tests might be defined in the same contract and share the same constructor. A possible solution is to generate a non-test version of a constructor (`TestName.init_symbolic` instead of `TestName.init`) if and only if we’re executing a non-test, and use it for non-tests.

**Comment by nwatson22** [comment]
@PetarMax @palinatolmach I experimented with the more symbolic versions of the constructors and am still trying to get their KCFGs to match up correctly with those of the functions being summarized, but I'm not convinced we need it.

Would it make sense to simply disable constructor calling and grafting except at the top level, by adding `new_prove_options.run_constructor = False` before the recursive call to `foundry_prove`, and then treating direct `kontrol prove` calls on non-test functions like `run_constructor` the same way treat tests, with the more concrete starting configuration?

I'm thinking this makes sense because if we're dealing with contracts that initialized in the test, e.g.
```
    function testIncrement() public {
        counter = new Counter();
```
by the time we get to 
```
        counter.increment();
```
the constructor for Counter has already been executed and the contract account is already in the configuration.

**Comment by PetarMax** [comment]
The goal of running constructors for CSE functions is to ensure that all of the storage/variables/immutables are initialised correctly. If a constructor manipulates the contract state in a specific way, this should be reflected in the initial states for CSE.

Note that CSE is run CSE is run separately from tests and needs to be both general enough so that when a contract is initialised as part of a test and the function called, the summary works, but also precise enough so as not to explore non-existent branches.

**Comment by palinatolmach** [comment]
@nwatson22 here's a slightly more detailed description of the issue as provided by @PetarMax: it manifests when running
```solidity
    function run_constructor() public {
        assert(flag);
    }
```
which is not a test, and so its constructor should be run with a symbolic `CONTRACT_ID`. However, it’s run with a concrete one (`Foundry.address_TEST_CONTRACT()`), since that’s what is done when a constructor is reached. This test fails with the `SLOAD 27` error. But when looking at the KCFG, there is this transition
```
┃  │  (2 steps)
┃  ├─ 10 (terminal)
┃  │   k: #halt ~> CONTINUATION:K
┃  │   pc: 69
┃  │   callDepth: 0
┃  │   statusCode: EVMC_SUCCESS
┃  │   src: test/ConstructorTest.t.sol:5:21
┃  │
┃  │  (1 step)
┃  ├─ 12
┃  │   k: #execute ~> CONTINUATION:K
┃  │   pc: 0
┃  │   callDepth: CALLDEPTH_CELL:Int
┃  │   statusCode: STATUSCODE:StatusCode
┃  │   src: test/ConstructorTest.t.sol:5:21
```
and the delta between them is significant, with everything that was concrete becoming symbolic (but should be symbolic, since the function executed is a non-test). For example:
```
          <callState>
            <program>
              ( SOME_CONCRETE_CODE => SOME_OTHER_CONCRETE_CODE )
            </program>
            <jumpDests>
              ( SOME_CONCRETE_JUMPDESTS => SOME_OTHER_CONCRETE_JUMPDESTS )
            </jumpDests>
            <id>
              ( 728815563385977040452943777879061427756277306518 => CONTRACT_ID:Int )
            </id>
            <caller>
              CALLER_ID:Int
            </caller>
            <callData>
              ( CALLDATA_CELL:Bytes => b"\xe0\x18\x0b\x0b" )
            </callData>
            <callValue>
              0
            </callValue>
            <wordStack>
              .WordStack
            </wordStack>
            <localMem>
              ( SOME_OTHER_CONCRETE_CODE => b"" )
            </localMem>
            <pc>
              ( 69 => 0 )
            </pc>
            <gas>
              0
            </gas>
            <memoryUsed>
              0
            </memoryUsed>
            <callGas>
              0
            </callGas>
            <static>
              ( false => STATIC_CELL:Bool )
            </static>
            <callDepth>
              ( 0 => CALLDEPTH_CELL:Int )
            </callDepth>
          </callState>
```
and this specifically
```
<id>
  ( 728815563385977040452943777879061427756277306518 => CONTRACT_ID:Int )
</id>
```
causes the proof to fail.
