### ISSUE TITLE
Skipping native assertions in expectRevert

### ISSUE THREAD

**Issue by anvacaru** [runtimeverification/kontrol#556]
According to the foundry book, [after calling expectRevert, calls to other cheatcodes before the reverting call are ignored.](https://book.getfoundry.sh/cheatcodes/expect-revert?highlight=expectRe)

However, when running a test like 
```Solidity
    function test_assertTrue_string() public {
        string memory err = "throw test";
        vm.expectRevert(bytes(err));
        assertTrue(false, err);
    }
```

the `vm.assertTrue` call is executed, while in kontrol it is skipped.
![image](https://github.com/runtimeverification/kontrol/assets/16517508/3a021b8e-4afb-4abe-93ca-5af6c0a86953)

**Comment by jinxinglim** [comment]
I have "forwarded" this issue to `forge-std` repository: https://github.com/foundry-rs/forge-std/issues/565. If there is no reply from them in a few days, I will follow up and text them in their telegram support group.

**Comment by jinxinglim** [comment]
### Update from Foundry team as of 10 June 2024

See comment: https://github.com/foundry-rs/foundry/issues/8049#issuecomment-2157102998

#### Reason for `expectRevert` to catch `assertTrue`

"""
`expectRevert` catches reverts on its depth or above. So, in your example it does not expect `assertTrue` call on depth 1 to revert, however, the revert of `assertTrue` is being propagated by Solidity to revert entire test contract call, thus causing a revert on depth 0 which `expectRevert` catches.
"""

#### Solution

"""
I see how this is confusing though, and this indeed will be fixed by v1 `expectRevert` changes
"""

**Comment by palinatolmach** [comment]
Moving to "Blocked" until the fix is implemented in Foundry and we can confirm that the behavior is consistent with Kontrol.

**Comment by jinxinglim** [comment]
I have updated the foundry version to https://github.com/foundry-rs/foundry/tree/nightly-7226aa06bbb473bfa7fabc0c92215c0938017d0c and tested this test function again

```solidity
    function test_assertTrue_string() public {
        string memory err = "throw test";
        vm.expectRevert(bytes(err));
        assertTrue(false, err);
    }
```

and it failed due to the following reason:
```
Ran 1 test for test/MinimalTest.t.sol:MinimalTest
[FAIL. Reason: call did not revert as expected] test_assertTrue_string() (gas: 14192)
Logs:
  Error: throw test
  Error: Assertion Failed

Traces:
  [14192] MinimalTest::test_assertTrue_string()
    ├─ [0] VM::expectRevert(throw test)
    │   └─ ← [Return] 
    ├─ emit log_named_string(key: "Error", val: "throw test")
    ├─ emit log(val: "Error: Assertion Failed")
    ├─ [0] VM::store(VM: [0x7109709ECfa91a80626fF3989D68f67F5b1DD12D], 0x6661696c65640000000000000000000000000000000000000000000000000000, 0x0000000000000000000000000000000000000000000000000000000000000001)
    │   └─ ← [Return] 
    └─ ← [Stop] 

Suite result: FAILED. 0 passed; 1 failed; 0 skipped; finished in 1.06ms (341.65µs CPU time
```

@palinatolmach and @anvacaru Is this issue safe to be closed? Are there any other follow up action to be taken for this?
