### ISSUE TITLE
Move `foundry.md` from `evm-semantics` to `kontrol`

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/kontrol#61]
Including corresponding kompilation logic.

**Comment by yale-vinson** [comment]
@tothtamas28 I am assuming that this is something for the backlog for us to get to eventually, or is there some urgency to it? Trying to triage it in advance of tomorrow's Stand Up.

**Comment by tothtamas28** [comment]
This is technical debt that we will always be able to work around, so it's not urgent in that sense. However, until it is resolved any change that requires modification of the K definition (e.g. adding a new cheat code) will take two PR's: one in `evm-semantics` (updating `foundry.md` + build script), and another one in `kontrol` (updating Python code, adding tests, etc).

**Comment by TheDutchDevil** [comment]
Apologies for barging in here. I encountered this issue while searching on GitHub for Technical Debt issues. My name is Nathan, and I'm a Software Engineering researcher affiliated with Eindhoven University of Technology.

Previously ([See](https://cassee.dev/files/satd-and-polarity.pdf)) we studied Technical Debt in OSS Java systems and used the technical debt present in these systems to design a taxonomy of different types of technical debt. Based on the discussion in this issue and the linked issues, this type of issue appears to be something we did not discover in our original taxonomy. 

**I'm posting in this issue because we're continuing our research into technical debt** and trying to understand better decisions made while managing technical debt. To that end, we've designed a small experiment, and since you're developers affected by technical debt I thought you might be interested in participating. You can take the survey online [here](https://tueapse.qualtrics.com/jfe/form/SV_39T0IWub1qC8cmy?Source=GitHub), and it should take you between 10 to 15 minutes. We hope that this experiment will allow us to understand technical debt better, and design more effective tools and methods for the management and identification of technical debt.

**Comment by tothtamas28** [comment]
I realized we first need to drop `kontrolx` from `evm-semantics`: https://github.com/runtimeverification/evm-semantics/issues/2113.
